config/routes.rb
Rails.application.routes.draw do
  get 'report_cards/index'

  devise_for :users
  root 'pages#index'
  resources :students, path: 'alumnos' do     
    resources :report_cards, path: 'boletas' do
      resources :detail_report_cards, path: 'detalle-boleta'
    end
  end
  resources :courses, path: 'cursos'
  resources :study_modules, path: 'modulos'


end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :detail_report_cards, dependent: :destroy
  has_and_belongs_to_many :study_modules, dependent: :destroy
end

app/models/detail_report_card.rb
class DetailReportCard < ActiveRecord::Base
  belongs_to :report_card
  belongs_to :course
end

app/models/report_card.rb
class ReportCard < ActiveRecord::Base
  belongs_to :student
  belongs_to :study_module
  has_many :detail_report_cards
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :report_cards
  def self.search(search)
    where("firstName LIKE ? OR lastName LIKE ? OR dni LIKE ? ", "%#{search}","%#{search}","%#{search}")
  end
end

app/models/study_module.rb
class StudyModule < ActiveRecord::Base
  has_many :report_cards
  has_and_belongs_to_many :courses
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  if Rails.env.production?
    devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  else
    devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_course, only: [:show, :edit ,:update, :destroy]
  def index
    @courses = Course.all
    @num = 0
  end

  def show
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new course_params
    if @course.save
      redirect_to courses_path, notice: 'El curso de ha creado correctamente'
    else
      redirect_to 'new', notice: 'Opps, ocurrio algun error'
    end
  end

  def edit
  end

  def update
    if @course.update course_params
      redirect_to @course, notice: 'Se actualizo correctamente'
    else
      redirect_to 'edit', notice: 'Opps, ocurrio algun error'
    end 
  end

  def destroy
    @course.destroy
    redirect_to courses_path
  end

  private 
  def course_params
    params.require(:course).permit(:name)
  end
  def find_course
    @course = Course.find(params[:id])
  end
end

app/controllers/detail_report_cards_controller.rb
class DetailReportCardsController < ApplicationController
  before_action :find_detail_report_card, only: [:update]
  def update
    if @detail_report_card.update detail_report_card_params
      
      render json: nil, status: :ok      
    end
  end
  private 
  def detail_report_card_params
    params.permit(:report_card_id,:course_id,:calification)
  end
  def find_detail_report_card
    @detail_report_card = DetailReportCard.find(params[:id])
  end
end

app/controllers/modules_controller.rb
class ModulesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/report_cards_controller.rb
class ReportCardsController < ApplicationController
  before_action :find_student
  before_action :find_report_card, only: [:show, :edit, :update, :destroy]
  def index
    @report_cards = @student.report_cards
    @num = 0
  end
  def show
    @detail_report_cards = @report_card.detail_report_cards
    @num = 0
    @final_average = 0
    totalNumber = 0
    number_courses = @detail_report_cards.length
    @detail_report_cards.each do |detail|
      totalNumber = totalNumber + detail.calification
    end
    @final_average = totalNumber/number_courses
    @report_card.final_average = @final_average
    @report_card.save


  end
  def edit
    @detail_report_cards = @report_card.detail_report_cards
  end

  private
  def find_student
    @student = Student.find(params[:student_id])
    
  end
  def find_report_card
    @report_card = ReportCard.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_student, only: [:show, :edit, :destroy, :update]
  def index
    @students = Student.all
    if params[:search]
      @students = Student.search(params[:search]).order("created_at DESC")
    else
      @students = Student.all
    end
  end 
  def new 
    @student = Student.new
  end
  def show

  end
  def create
    @student = Student.new student_params
    if @student.save
      
      generateReportCard(@student)
      redirect_to students_path, notice: "Bien, se creo el estudiante"
    else 
      render 'new', notice: "Ocurrió un error, por favor verique bien los datos"
    end
  end
  def edit
  end
  def update
    if @student.update student_params
      redirect_to @student, notice: 'Se actualizo correctamente'
    else
      redirect_to 'edit', notice: 'Ocurio algun tipo de error'
    end
  end
  def destroy
    @student.destroy
    redirect_to students_path
  end


  private
  def student_params
    params.require(:student).permit(:code,:firstName,:lastName,:age, :dni, :firstModule)
  end

  def find_student
    @student = Student.find(params[:id])
  end

  def generateReportCard(student)
    
    @study_modules = StudyModule.all
    @study_modules.each do |study_module|
      @report_card = ReportCard.new
      @report_card.student = student
      @report_card.study_module = study_module
      @report_card.save
      study_module.courses.each do |course|
        @detail_report_card = DetailReportCard.new
        @detail_report_card.report_card = @report_card
        @detail_report_card.course = course
        @detail_report_card.calification = 0  
        @detail_report_card.save
      end
    end

  end
end

app/controllers/study_modules_controller.rb
class StudyModulesController < ApplicationController
  before_action :find_study_module, only: [:show, :edit, :update, :destroy]
  def index
    @study_modules = StudyModule.all
  end
  def new
    @study_module = StudyModule.new
    @courses = Course.all
  end
  def create
    @study_module = StudyModule.new study_module_params
    if @study_module.save
      redirect_to study_modules_path, notice: 'Se creó correctamente'
    else
      render 'new', notice: 'Ocurrio un error'
    end
  end
  def edit
    @courses = Course.all
  end
  def show

  end
  def update
    if @study_module.update study_module_params
      redirect_to study_modules_path, notice: 'se actualizo correctamente'
    else
      redirect_to 'edit', notice: 'Ocurrio algun error'
    end
  end
  def destroy
     @study_module.destroy
     redirect_to study_modules_path   
  end
  private
  def study_module_params
    params.require(:study_module).permit(:name, {course_ids:[]})
  end
  def find_study_module
    @study_module = StudyModule.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/detail_report_cards_helper.rb
module DetailReportCardsHelper
end

app/helpers/detailreportcard_helper.rb
module DetailreportcardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/report_cards_helper.rb
module ReportCardsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/study_modules_helper.rb
module StudyModulesHelper
end

app/views/courses/_form.html.erb
<%= form_for @course, html: { class: 'pure-form pure-form-stacked'} do |f|%>
 <% if @course.errors.any? %>
    <h2><%= pluralize(@course.errors.count, "Error") %></h2>
    <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="pure-control-group">
    <%= f.label :name, 'Nombre' %>
    <%= f.text_field :name, required: :true %>
  </div>
  <div class="pure-control-group">
    <%= f.submit 'Guardar', class: 'button success' %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1 class="center"> Editar Curso </h1>

<%= render 'form' %>
<br>

<%= link_to 'Regresar a cursos', courses_path, class: 'button-secondary pure-button ' %>

app/views/courses/index.html.erb
<h2 class="center">Lista de Cursos</h2>
<table class="pure-table pure-table-horizontal">
  <thead>
    <tr>
      <th>#</th>  
      <th>Nombre</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= @num = @num + 1 %></td>
        <td><%= course.name %></td>
        <td><%= link_to 'Editar', edit_course_path(course),class: 'label' %> - <%= link_to 'Ver', course_path(course), class: 'label success' %> - <%= link_to 'Eliminar', course_path(course), class: 'label alert' ,method: :delete, data: {confirm: 'Esta seguro?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Nuevo Curso', new_course_path, class: 'button' %>

app/views/courses/new.html.erb
<h1 class="center"> Nuevo Curso </h1>

<%= render 'form' %>
<br>
<%= link_to 'Regresar a cursos', courses_path, class: 'button' %>

app/views/courses/show.html.erb
<h2 class="center"> Curso </h2>
<p> <strong> Nombre : <%= @course.name %></strong></p>

<%= link_to 'Regresar a cursos', courses_path, class: 'button' %>

app/views/report_cards/edit.html.erb
<h1 class="center">Boleta de Notas</h1>

<div class="ReportCard">
  <div class="ReportCard-head">
    <h3 class="ReportCard-mainTitle">INSTITUTO TÉCNICO DE OPERADORES MINEROS OPERMINE</h3>
    <p class="ReportCard-subheader">ESPECIALISTAS EN OPERACIONES MINERAS MAQUINARIA PESADA</p>
    <p class="ReportCard-subsubheader"> CENTRO DE EDUCACIÓN TECNICO PRODUCTIVO</p>
    <%= image_tag 'logo-ministerio-educacion-peru.png', class: 'ReportCard-ministeryLogo' %>
    <%= image_tag 'logo-opermine.png', class: 'ReportCard-imgLogo' %>
    <h2 class="ReportCard-title">RESULTADOS ACADÉMICOS</h2>
    <p class="ReportCard-subtitle"> PROGRAMA DE CAPACITACIÓN TÉCNICA</p>
    <p class="ReportCard-headNameModule"> En <%= @report_card.study_module.name %></p>
  </div>
  <div class="ReportCard-details">
    <p><strong>ALUMNO (A)</strong> : <%= @report_card.student.firstName%> <%= @report_card.student.lastName%></p>
    <p><strong>CODIGO DE ALUMNO</strong> : <%= @report_card.student.code%> </p>
    <p><strong>CERTIFICADO Nº </strong> : <%= @report_card.id %> </p>
    <p><strong>PROGRAMA TÉCNICO Nº </strong> : TRANSPORTE TERRESTRE Y OPERACION DE EQUIPO PESADO </p>
    <p><strong>MÓDULO Nº </strong> : <%= @report_card.study_module.name %> </p>
    <p>HABIENDO OBTENIDO LAS SIGUIENTES CALIFICACIONES  </p>
  </div>
  <div class="ReportCard-contentCalifactions">
    <table class="ReportCard-tableCalifications">
      <thead>
        <tr>
          <th>Nº</th>
          <th>CURSOS DESARROLLADOS</th>
          <th width="140">PROMEDIO</th>
          <th width="250">OBS.</th>
        </tr>
      </thead>
      <tbody>
        
        <% @detail_report_cards.each do |detail|%>
        <tr>
          <td><%= detail.course.id %></td>
          <td><%= detail.course.name %></td>
          <td>
            <input data-detail="<%= detail.id %>" data-course="<%= detail.course_id%>" class="calification" type="text" value="<%= detail.calification %>">
          </td>
          <td >
            
          </td> 
        </tr>
        <% end %>
      </tbody>
    </table>
    <p class="ReportCard-date">
      <strong>Fecha de entrega : </strong> <%= DateTime.now.strftime("%d/%m/%Y") %>
    </p>
  </div>
  <div class="ReportCard-footer">
    <div class="ReportCard-firm">
      <div class="ReportCard-firmText">
        <p>Firma y Sello</p>
        <p>Director</p>
      </div>
    </div>
    <div class="ReportCard-firm">
      <div class="ReportCard-firmText">
        <p>Firma y Sello</p>
        <p>Coordinación academica</p>
      </div>
    </div>
  </div>
</div>
<br>
<%= link_to 'Regresar a Boletas', student_report_cards_path(@student), class: 'button' %>

app/views/report_cards/index.html.erb
<h1 class="center">Boleta de Notas</h1>
<b>Nombre: </b>
<p><%= @student.firstName %> <%= @student.lastName %></p>

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Programa técnico</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @report_cards.each do |report_card| %>
      <tr>
        <td><%= @num = @num + 1 %></td>
        <td><%= report_card.study_module.name %></td>
        <td><%= link_to 'Ver', student_report_card_path(@student, report_card), class: 'label success' %> <%= link_to 'Añadir notas', edit_student_report_card_path(@student, report_card), class: 'label' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Regresar a Alumnos', students_path, class: 'button' %>

app/views/report_cards/show.html.erb
<h1 class="center">Boleta de Notas</h1>

<div class="ReportCard">
  <div class="ReportCard-head">
    <h3 class="ReportCard-mainTitle">INSTITUTO TÉCNICO DE OPERADORES MINEROS OPERMINE</h3>
    <p class="ReportCard-subheader">ESPECIALISTAS EN OPERACIONES MINERAS MAQUINARIA PESADA</p>
    <p class="ReportCard-subsubheader"> CENTRO DE EDUCACIÓN TECNICO PRODUCTIVO</p>
    <%= image_tag 'logo-ministerio-educacion-peru.png', class: 'ReportCard-ministeryLogo' %>
    <%= image_tag 'logo-opermine.png', class: 'ReportCard-imgLogo' %>
    <h2 class="ReportCard-title">RESULTADOS ACADÉMICOS</h2>
    <p class="ReportCard-subtitle"> PROGRAMA DE CAPACITACIÓN TÉCNICA</p>
    <p class="ReportCard-headNameModule"> En <%= @report_card.study_module.name %></p>
  </div>
  <div class="ReportCard-details">
    <p><strong>ALUMNO (A)</strong> : <%= @report_card.student.firstName%> <%= @report_card.student.lastName%></p>
    <p><strong>CODIGO DE ALUMNO</strong> : <%= @report_card.student.code%> </p>
    <p><strong>CERTIFICADO Nº </strong> : <%= @report_card.id %> </p>
    <p><strong>PROGRAMA TÉCNICO Nº </strong> : TRANSPORTE TERRESTRE Y OPERACION DE EQUIPO PESADO </p>
    <p><strong>MÓDULO Nº </strong> : <%= @report_card.study_module.name %> </p>
    <p>HABIENDO OBTENIDO LAS SIGUIENTES CALIFICACIONES  </p>
  </div>
  <div class="ReportCard-contentCalifactions">
    <table class="ReportCard-tableCalifications">
      <thead>
        <tr>
          <th>Nº</th>
          <th>CURSOS DESARROLLADOS</th>
          <th>PROMEDIO</th>
          <th>OBS.</th>
        </tr>
      </thead>
      <tbody>
        
        <% @detail_report_cards.each do |detail|%>
        <tr>
          <td><%= @num = @num + 1 %></td>
          <td><%= detail.course.name %></td>
          <% if detail.calification >12 %>
            <td class="blue bold">
              <%= detail.calification %>
            </td>
          <% else %>
            <td class="red">
              <%= detail.calification %>
            </td>
          <% end %>
          <td></td> 
        </tr>
        <% end %>
        <tr>
          <th></th>
          <th>PROMEDIO FINAL DEL CURSO</th>
          <th> 
            <%= '%.2i' %@final_average %> 
          </th>
        </tr>
      </tbody>
    </table>
    <p class="ReportCard-date">
      <strong>Fecha de entrega : </strong> <%= DateTime.now.strftime("%d/%m/%Y") %>
    </p>
  </div>
  <div class="ReportCard-footer">
    <div class="ReportCard-firm">
      <div class="ReportCard-firmText">
        <p>Firma y Sello</p>
        <p>Director</p>
      </div>
    </div>
    <div class="ReportCard-firm">
      <div class="ReportCard-firmText">
        <p>Firma y Sello</p>
        <p>Coordinación academica</p>
      </div>
    </div>
  </div>
</div>

<a href="#" onclick="window.print();" class="print button">
    Imprimir
    <i class="fa fa-print"></i>
</a>
<br>
<%= link_to 'Regresar a Boletas', student_report_cards_path(@student), class: 'button' %>

app/views/students/_form.html.erb
<%= form_for @student, html: { class: 'pure-form pure-form-stacked'} do |f| %>
  <% if @student.errors.any? %>
    <h2><%= pluralize(@student.errors.count, "Error") %></h2>
    <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="pure-control-group">
    <%= f.label :code, 'Codigo' %>
    <%= f.text_field :code, required: :true %>
  </div>
  <div class="pure-control-group">
    <%= f.label :firstName, 'Nombre'  %>
    <%= f.text_field :firstName, required: :true %>
  </div>
  <div class="pure-control-group">
    <%= f.label :lastName, 'Apellidos' %>
    <%= f.text_field :lastName, required: :true %>
  </div>
  <div class="pure-control-group">
    <%= f.label :age, 'Edad' %>
    <%= f.number_field :age, required: :true %>
  </div>
  <div class="pure-control-group">
    <%= f.label :dni, 'DNI' %>
    <%= f.text_field :dni, required: :true %>
  </div>
  <div class="pure-control-group">
    <%= f.label :firstModule, 'Primer Módulo' %>
    <%= f.text_field :firstModule, required: :true %>
  </div>
  <div class="pure-control">
    <%= f.submit 'Guardar' , class: 'button success' %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1 class="center">Editar Alumno</h1>

<%= render 'form' %>
<br>
<%= link_to 'Regresar a Alumnos', students_path, class: 'button' %>

app/views/students/index.html.erb
<%= form_tag(students_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Buscar Alumnos" %>
  <%= submit_tag "Buscar", class: "button" %>
<% end %>
<h1 class="center">Lista de Alumnos</h1>
  <table>
    <thead>
      <tr>
        <th>Código</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Edad</th>
        <th>DNI</th>
        <th>Fecha</th>
        <th>Primer Módulo</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.code %></td>
          <td><%= student.firstName %></td>
          <td><%= student.lastName %></td>
          <td><%= student.age %></td>
          <td><%= student.dni %></td>
          <td><%= student.created_at.strftime("%m/%Y")  %> </td>
          <td><%= student.firstModule%> </td>
          <td><%= link_to 'Ver' , student_path(student), class: 'label success' %> <%= link_to 'Editar', edit_student_path(student), class: 'label'%> <%= link_to 'Boleta de Notas' , student_report_cards_path(student), class: 'label'%> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<br>
<%= link_to 'Nuevo Alumno', new_student_path , class: 'button' %>

app/views/students/new.html.erb
<h1 class="center"> Nuevo Alumno</h1>
<div>
  <%= render 'form' %>
</div>
<%= link_to 'Regresar a Alumnos', students_path, class: 'button' %>

app/views/students/show.html.erb
<h2><%= @student.firstName %></h2>
<h4><%= @student.lastName %></h4>
<p><strong> Codigo: </strong> <%= @student.code %></p>
<p><strong> DNI: </strong> <%= @student.dni %></p>
<p><strong> Edad: </strong> <%= @student.age %></p>
<p><strong> Fecha de Inicio: </strong> <%= @student.created_at %></p>
<p><strong> Primer Módulo: </strong> <%= @student.firstModule %></p>
<%= link_to 'Regresar a Alumnos', students_path, class: 'button' %>

app/views/study_modules/_form.html.erb
<%= form_for @study_module, html: {class: 'pure-form pure-form-stacked'} do |f| %>
  <% if @study_module.errors.any? %>
    <h2> <%= pluralize(@study_module.errors.count, "Error") %></h2>
    <ul>
      <% @study_module.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="pure-control-group">
    <%= f.label :name, 'Nombre'%>
    <%= f.text_field :name %>
  </div>
  <h4>Cursos Pertenecientes: </h4>
  <div class="pure-control-group">
    <%= label_tag "Cursos" %>
    <%= hidden_field_tag "study_module[course_ids][]", nil %>
    <% @courses.each do |course| %>
      <p><%= check_box_tag "study_module[course_ids][]", course.id, @study_module.courses.include?(course) %> <%= course.name %></p>
    <% end %>
  </div>
  

  <div class="pure-control-group">
    <%= f.submit 'Guardar' , class: 'button success' %>
  </div>
<% end %>

app/views/study_modules/edit.html.erb
<h1 class="center">Editar Módulo</h1>
<%= render 'form' %>
<%= link_to 'Regresar a modulos', study_modules_path, class: 'button' %>

app/views/study_modules/index.html.erb
<h1 class="center">Nuevo Módulo</h1>
<table>
  <thead>
    <tr>
      <th>
        #
      </th>
      <th>Nombre</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @study_modules.each do |study_module|%>
    <tr>
      <td><%= study_module.id%></td>
      <td><%= study_module.name %></td>
      <td>
        <%= link_to 'Editar', edit_study_module_path(study_module), class: 'label' %>
        <%= link_to 'Eliminar', study_module_path(study_module), method: :delete, data: {confirm: 'Esta seguro'}, class: 'label alert' %>
        <%= link_to 'Ver', study_module_path(study_module), class: 'label success' %>
      </td>
    </tr>
    <% end %> 
  </tbody>
</table>
<br>
<%= link_to 'Nuevo Módulo', new_study_module_path, class: 'button' %>

app/views/study_modules/new.html.erb
<h1 class="center"> Nuevo Módulo </h1>
<%= render 'form' %>
<%= link_to 'Regresar a Módulos', study_modules_path, class: 'button' %>

app/views/study_modules/show.html.erb
<h1>Nombre: <%= @study_module.name %></h1>
<%= link_to 'Regresar a modulos', study_modules_path, class: 'button'%>