config/routes.rb
Rails.application.routes.draw do
  get 'report_cards/index'

  devise_for :users
  root 'pages#index'
  resources :students, path: 'alumnos' do     
    resources :report_cards, path: 'boletas' do
      resources :detail_report_cards, path: 'detalle-boleta'
    end
  end
  resources :courses, path: 'cursos'
  resources :study_modules, path: 'modulos'


end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :detail_report_cards, dependent: :destroy
  has_and_belongs_to_many :study_modules, dependent: :destroy
end

app/models/detail_report_card.rb
class DetailReportCard < ActiveRecord::Base
  belongs_to :report_card
  belongs_to :course
end

app/models/report_card.rb
class ReportCard < ActiveRecord::Base
  belongs_to :student
  belongs_to :study_module
  has_many :detail_report_cards
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :report_cards
  def self.search(search)
    where("firstName LIKE ? OR lastName LIKE ? OR dni LIKE ? ", "%#{search}","%#{search}","%#{search}")
  end
end

app/models/study_module.rb
class StudyModule < ActiveRecord::Base
  has_many :report_cards
  has_and_belongs_to_many :courses
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  if Rails.env.production?
    devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  else
    devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_course, only: [:show, :edit ,:update, :destroy]
  def index
    @courses = Course.all
    @num = 0
  end

  def show
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new course_params
    if @course.save
      redirect_to courses_path, notice: 'El curso de ha creado correctamente'
    else
      redirect_to 'new', notice: 'Opps, ocurrio algun error'
    end
  end

  def edit
  end

  def update
    if @course.update course_params
      redirect_to @course, notice: 'Se actualizo correctamente'
    else
      redirect_to 'edit', notice: 'Opps, ocurrio algun error'
    end 
  end

  def destroy
    @course.destroy
    redirect_to courses_path
  end

  private 
  def course_params
    params.require(:course).permit(:name)
  end
  def find_course
    @course = Course.find(params[:id])
  end
end

app/controllers/modules_controller.rb
class ModulesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/report_cards_controller.rb
class ReportCardsController < ApplicationController
  before_action :find_student
  before_action :find_report_card, only: [:show, :edit, :update, :destroy]
  def index
    @report_cards = @student.report_cards
    @num = 0
  end
  def show
    @detail_report_cards = @report_card.detail_report_cards
    @num = 0
    @final_average = 0
    totalNumber = 0
    number_courses = @detail_report_cards.length
    @detail_report_cards.each do |detail|
      totalNumber = totalNumber + detail.calification
    end
    @final_average = totalNumber/number_courses
    @report_card.final_average = @final_average
    @report_card.save


  end
  def edit
    @detail_report_cards = @report_card.detail_report_cards
  end

  private
  def find_student
    @student = Student.find(params[:student_id])
    
  end
  def find_report_card
    @report_card = ReportCard.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_student, only: [:show, :edit, :destroy, :update]
  def index
    @students = Student.all
    if params[:search]
      @students = Student.search(params[:search]).order("created_at DESC")
    else
      @students = Student.all
    end
  end 
  def new 
    @student = Student.new
  end
  def show

  end
  def create
    @student = Student.new student_params
    if @student.save
      
      generateReportCard(@student)
      redirect_to students_path, notice: "Bien, se creo el estudiante"
    else 
      render 'new', notice: "Ocurrió un error, por favor verique bien los datos"
    end
  end
  def edit
  end
  def update
    if @student.update student_params
      redirect_to @student, notice: 'Se actualizo correctamente'
    else
      redirect_to 'edit', notice: 'Ocurio algun tipo de error'
    end
  end
  def destroy
    @student.destroy
    redirect_to students_path
  end


  private
  def student_params
    params.require(:student).permit(:code,:firstName,:lastName,:age, :dni, :firstModule)
  end

  def find_student
    @student = Student.find(params[:id])
  end

  def generateReportCard(student)
    
    @study_modules = StudyModule.all
    @study_modules.each do |study_module|
      @report_card = ReportCard.new
      @report_card.student = student
      @report_card.study_module = study_module
      @report_card.save
      study_module.courses.each do |course|
        @detail_report_card = DetailReportCard.new
        @detail_report_card.report_card = @report_card
        @detail_report_card.course = course
        @detail_report_card.calification = 0  
        @detail_report_card.save
      end
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/detail_report_cards_helper.rb
module DetailReportCardsHelper
end

app/helpers/detailreportcard_helper.rb
module DetailreportcardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/report_cards_helper.rb
module ReportCardsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/study_modules_helper.rb
module StudyModulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sistema de Notas Opermine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>
<div class="Layout">
  <%= render 'partials/header' %>
  <div class="Layout-mainContent">
    <div class="Content">  
      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/pages/index.html.erb
<div class="Main">
  <div class="Main-welcome">
    <div class="Welcome">
      <div class="Welcome-top">
        <div class="LogoPage">
          <%= image_tag 'logo-opermine.png', class: "LogoPage-image" %>
        </div>
        <h1 class="Welcome-title">Sistema de Notas Opermine</h1>
      </div>
      <div class="Welcome-actions"> 
        <% if user_signed_in? %>
          <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: 'button-xlarge pure-button pure-button-primary' %>
        <% else %>  
          <%= link_to 'Ingresar', new_user_session_path, class: 'button-xlarge pure-button pure-button-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/partials/_header.html.erb
<div class="Layout-header">
  <nav class="MainHeader">
    <div class="MainHeader-logo">
      <div class="Logo">
        <%= image_tag 'logoNormal.png', class: 'Logo-img' %>
      </div>
    </div>
    <div class="MainHeader-links">
      <div class="Enlaces">
        <ul class="Enlaces-list">
          <li class="Enlaces-item">
            <%= link_to 'Inicio', root_path, class: 'Enlaces-link'  %>
          </li>
          <li class="Enlaces-item">
            <%= link_to 'Alumnos', students_path, class: 'Enlaces-link'  %>
          </li>
          <li class="Enlaces-item">
            <%= link_to 'Módulos', study_modules_path, class: 'Enlaces-link'  %>
          </li>
          <li class="Enlaces-item">
            <%= link_to 'Cursos', courses_path, class: 'Enlaces-link'  %>
          </li>
          <% if user_signed_in? %>
            <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: 'Enlaces-link' %>
            <% else %>  
            <%= link_to 'Ingresar', new_user_session_path, class: 'Enlaces-link' %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>